apiVersion: v1
kind: Service
metadata:
  name: es-nodeport
spec:
  type: NodePort
  selector:
    app: elasticsearch-master # elasticsearchのlabelを指定
  ports:
  - port: 9200
    targetPort: 9200 # elasticsearchがlistenしているportを指定
